app:
  services:
    exchangeratesapi: https://api.exchangeratesapi.io/
    frankfurter: https://api.frankfurter.app/
    ratesapi: https://api.ratesapi.io/
  retrofit:
    timeout: 5000
    logging: BASIC
    

logging:
  level: 
    root: INFO
    demo: DEBUG
    
hystrix:  dashboard:    proxy-stream-allow-list:    - "localhost"
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
